[package]
name = "cargo-llvm-cov"
version = "0.1.0-alpha.5"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/taiki-e/cargo-llvm-cov"
keywords = ["cargo", "coverage", "subcommand", "testing"]
categories = ["command-line-utilities", "development-tools", "development-tools::cargo-plugins", "development-tools::testing"]
exclude = ["/.*", "/tools"]
description = """
Cargo subcommand for LLVM source-based code coverage (-Z instrument-coverage).
"""

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[workspace]
resolver = "2"

[dependencies]
anyhow = "1.0.34"
atty = "0.2.11"
camino = "1"
cargo_metadata = "0.14"
clap = "=3.0.0-beta.2"
dirs-next = "2"
duct = "0.13.1"
glob = "0.3"
is_executable = "1"
open = "2"
regex = { version = "1.3", default-features = false, features = ["perf", "std"] }
rustc-demangle = "0.1.19"
serde = { version = "1.0.103", features = ["derive"] }
serde_json = "1"
shell-escape = "0.1.5"
termcolor = "1.1"
tracing = { version = "0.1.21", default-features = false, features = ["std"] }
tracing-subscriber = { version = "0.2.16", default-features = false, features = ["ansi", "env-filter"] }
walkdir = "2"

# This is needed for -Z minimal-versions.
lazy_static = "1.4"

[dev-dependencies]
easy-ext = "0.2"
fs-err = "2"
once_cell = "1"
tempfile = "3"
