[package]
name = "cargo-llvm-cov"
version = "0.1.0"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/taiki-e/cargo-llvm-cov"
keywords = ["cargo", "subcommand"]
categories = ["command-line-utilities", "development-tools::cargo-plugins"]
description = """
A wrapper for source based code coverage (-Zinstrument-coverage).
"""

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[workspace]

[dependencies]
anyhow = "1.0.20"
cargo_metadata = "0.12"
duct = "0.13"
fs-err = "2"
glob = "0.3"
is_executable = "1"
open = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
structopt = "0.3.20"
termcolor = "1"
toml = "0.5.2"
